plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'com.streamertest'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    junitVersion        = '5.11.4'
    testcontainersVersion = '1.20.4'
    allureVersion       = '2.29.0'
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testRuntimeOnly    'org.junit.platform:junit-platform-launcher'

    testImplementation "org.testcontainers:testcontainers:${testcontainersVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testcontainersVersion}"

    testImplementation "io.qameta.allure:allure-junit5:${allureVersion}"
}

allure {
    version = allureVersion
    adapter {
        aspectjWeaver = true
        autoconfigure = true
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
